package newtestleaf.Foundation;

import org.junit.Test;

import junit.framework.Assert;

public class FindTheDifference {
    /*
    You are given two strings s and t.
    String t is generated by random shuffling string s and
    then add one more letter at a random position. Return the letter that was added to t.
        Example 1:
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.
    Example 2:

    Input: s = "", t = "y"
    Output: "y" */

    @Test
    public void test1() {
        char actual = findTheDiff("abcd", "abcde");
        Assert.assertEquals(actual, 'e');
    }

    @Test
    public void test2() {
        char actual = findTheDiff("", "y");
        Assert.assertEquals(actual, 'e');
    }

    public char findTheDiff(String s, String t) {
        //Initialize an int array with ASCII length (128)
        int[] arr = new int[128];
        //s = "abcd"
        for (char ch : s.toCharArray()) {
            //[0,0,0 ...1(97),1(98),1,1,0,0 ]
            arr[ch]++;
        }
        //t = "abcde"
        for (char ch : t.toCharArray()) {
            //[all 1 from above will become zero for abcd and e will become -1]
            arr[ch]--;
        }
        for (int i = 0; i < arr.length; i++) {
            if (arr[i] == -1) {
                return (char) i;
            }
        }
        return ' ';
    }
}
